### ISSUE TITLE
Launch Time

### ISSUE THREAD

**Issue by CrazyMarvin** [Crazy-Marvin/ProductHuntTelegramBot#6]
> Our website works as per pacific timings and new products are launched at the midnight (12:01 AM PST). However, if you are thinking of sending a notification to the users, I'd recommend waiting for 5-6 hours after the launch hour because some users also schedule major launches at 6/7 AM PST :)

**Comment by tech-savvy-guy** [comment]
![image](https://user-images.githubusercontent.com/83786816/139702610-a2509cd5-5e77-42ed-bc81-d2754785b1d3.png)

The server on which the bot is hosted on has the default UTC time zone. Now, I converted the time to match the needs. But I think the monthly updates should be kept at 00:00 PST cause otherwise both updates will be simultaneous...

Kindly confirm the following changes:

![image](https://user-images.githubusercontent.com/83786816/139704922-70de5dd2-723c-4d2c-b940-737de8e4b309.png)

**Comment by tech-savvy-guy** [comment]
I have pushed the new changes to the server. Hope this helps :)

Let me know if you need anything else :)

**Comment by CrazyMarvin** [comment]
Thanks for the update. 👍

I will ask Product Hunt if there is a recommended time for the monthly updates. I agree that it should be at another time.

**Comment by tech-savvy-guy** [comment]
Is this the perfect timing? #8

**Comment by CrazyMarvin** [comment]
The timing is working great for me since almost one year. Let's keep it that way. 

If someone should experiences issues, please comment here.
